//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLDT_lession09_Entity_Framework___Database_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NldtSinhVien
    {
        public string NldtMaSV { get; set; }
        public string NldtTen { get; set; }
        public string NldtHo { get; set; }
        public Nullable<System.DateTime> NldtPhai { get; set; }
        public Nullable<bool> NldtNgaysinh { get; set; }
        public string NldtNoiSinh { get; set; }
        public string NldtMaKH { get; set; }
        public string NldtHocBong { get; set; }
        public Nullable<decimal> NldtDiemTrungBinh { get; set; }
    }
}
