//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLDT_lession09_Entity_Framework___Database_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NldtKetQua
    {
        public string NldtmaSV { get; set; }
        public string NldtMaMH { get; set; }
        public string NldtDiem { get; set; }
    }
}
